export enum TypeProcess {
  LOGIN = "INICIAR_SESION",
  INSERT = "REGISTRAR",
  UPDATE = "MODIFICAR",
  DELETE = "ELIMINAR",
  READ = "BUSCAR",
  GET = "OBTENER",

  //   LOGOUT = "MODIFICAR_USUARIO",
}
